name: unsplash
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.6
  flutter_staggered_grid_view: ^0.7.0
  gallery_saver: ^2.3.2
  path_provider: ^2.0.11
  http: ^0.13.3
  http_interceptor: ^1.0.2
  logger: ^2.4.0





dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Metroplex Shadow
      fonts:
        - asset: assets/fonts/Metroplex Shadow.ttf
